# Generated by Django 4.1.2 on 2023-04-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserSection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsPoint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeId', models.IntegerField(max_length=10)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSection.user')),
                ('passengerId', models.ManyToManyField(related_name='rides_taken', to='UserSection.user')),
            ],
        ),
    ]
