# Generated by Django 4.1.2 on 2023-05-18 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0002_alter_vehicle_capacity'),
        ('MapSection', '0003_rename_end_route_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSection.driver'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='passengerId',
        ),
        migrations.AddField(
            model_name='route',
            name='passengerId',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='UserSection.passenger'),
            preserve_default=False,
        ),
    ]
