# Generated by Django 4.1.2 on 2023-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapSection', '0004_alter_route_driverid_remove_route_passengerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driverId',
        ),
        migrations.RemoveField(
            model_name='route',
            name='passengerId',
        ),
        migrations.RemoveField(
            model_name='route',
            name='routeId',
        ),
        migrations.RemoveField(
            model_name='route',
            name='routePoints',
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(max_length=200),
        ),
    ]
