# Generated by Django 4.1.2 on 2023-04-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
