# Generated by Django 4.1.2 on 2023-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0002_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
