# Generated by Django 4.1.2 on 2023-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
