# Generated by Django 4.1.2 on 2023-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0005_remove_admin_id_user_id_alter_admin_user_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(max_length=100),
        ),
    ]
