# Generated by Django 4.1.2 on 2023-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0006_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
