# Generated by Django 4.1.2 on 2023-05-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSection', '0007_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
