# Generated by Django 4.1.2 on 2023-04-27 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@eafit\\.edu\\.co$', 'Enter a valid eafit.edu.co email address.')])),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('homeAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('licensePlate', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('driverId', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='UserSection.user')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
            ],
            bases=('UserSection.user',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserSection.user')),
                ('pickup', models.CharField(max_length=200)),
                ('dropoff', models.CharField(max_length=200)),
            ],
            bases=('UserSection.user',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserSection.user')),
                ('driverLicense', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSection.vehicle')),
            ],
            bases=('UserSection.user',),
        ),
    ]
